analyzer:
  strong-mode: true

linter:
  rules:
    # errors
    - annotate_overrides
    - avoid_empty_else
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - control_flow_in_finally
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - test_types_in_equals
    - throw_in_finally
    - unrelated_type_equality_checks
    - valid_regexps
    # style rules
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_require_non_null_named_parameters
    - avoid_annotating_with_dynamic
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_null_checks_in_equality_operators
    - avoid_return_types_on_setters
    - avoid_returning_null
    - avoid_returning_this
    - await_only_futures
    - camel_case_types
    - constant_identifier_names
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - implementation_imports
    - join_return_with_assignment
    - library_names
    - library_prefixes
    - overridden_fields
    - package_api_docs
    - package_prefixed_library_names
    - prefer_adjacent_string_concatenation
    - prefer_conditional_assignment
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_initializing_formals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - recursive_getters
    - slash_for_doc_comments
    - super_goes_last
    - type_init_formals
    - unawaited_futures
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_this
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    # pub rules
    - package_names
