name: euler
version: 0.0.5

author: Lukas Renggli <renggli@gmail.com>
description: My advances on Project Euler.
homepage: https://github.com/renggli/dart-euler

environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  test: any
  more: any
