name: euler
version: 0.0.2
author: Lukas Renggli <renggli@gmail.com>
description: My advances on Project Euler.
homepage: https://github.com/renggli/dart-euler
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  junitconfiguration: any
  more: any
  unittest: any
