name: euler
version: 0.0.6

description: My advances on Project Euler.
homepage: https://github.com/renggli/dart-euler

environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependencies:
  more: ^3.0.0-nullsafety
  test: ^1.16.0-nullsafety
dependency_overrides:
  more:
    path: ../MoreDart