name: euler
version: 0.0.7

description: My advances on Project Euler.
homepage: https://github.com/renggli/dart-euler

environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependencies:
  data: ^0.7.0
  more: ^3.0.0
  petitparser: ^4.0.0
  test: ^1.16.0
