name: ProjectEuler
version: 0.0.1
author: Lukas Renggli <renggli@gmail.com>
description: My advances on the Project Euler.
homepage: https://github.com/renggli/ProjectEuler
dependencies:
  junitconfiguration: any
  more: any
  unittest: any
